version: "3.9"

networks:
  deploy-bikebuddy-dev:
    driver: bridge

services:
  bikebuddy_api:
    container_name: bikebuddy_api
    image: yarila/bikebuddybackend-bikebuddy_api:latest
    networks:
      - deploy-bikebuddy-dev
    depends_on:
      - postgres_db 
      - hangfire_db
      - minio 

  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: BikeBuddyDb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5445:5432
    networks:
        - deploy-bikebuddy-dev
    volumes:
        - postgres-data:/var/lib/postgresql/data 

  hangfire_db:
    container_name: hangfire_db
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: HangfireDb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5446:5432
    networks:
        - deploy-bikebuddy-dev
    volumes:
        - hangfire-data:/var/lib/postgresql/data

  minio:
    container_name: bikebuddy_minio
    image: quay.io/minio/minio
    restart: always
    ports:
        - "9000:9000" 
        - "9001:9001"  
    environment:
      MINIO_ROOT_USER: minioadmin  
      MINIO_ROOT_PASSWORD: minioadmin  
    volumes:
        - minio-data:/data 
    command: server /data --console-address ":9001"
    networks:
        - deploy-bikebuddy-dev

volumes:
    postgres-data:
    hangfire-data:
    minio-data: