version: "3.9"

networks:
  deploy-bikebuddy-dev:
    driver: bridge

services:
  bikebuddy_api:
    container_name: bikebuddy_api
    build:
      context: .
      dockerfile: src/BikeBuddy.API/Dockerfile
    networks:
      - deploy-bikebuddy-dev
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: BikeBuddyDb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5445:5432
    networks:
        - deploy-bikebuddy-dev
    volumes:
        - postgres-data:/var/lib/postgresql/data 

volumes:
    postgres-data: